export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST'
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS'
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL'

export const INVESTMENT_DETAILED_REQUEST = 'INVESTMENT_DETAILED_REQUEST'
export const INVESTMENT_DETAILED_SUCCESS = 'INVESTMENT_DETAILED_SUCCESS'
export const INVESTMENT_DETAILED_FAIL = 'INVESTMENT_DETAILED_FAIL'
