export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILED_REQUEST = 'ORDER_DETAILED_REQUEST'
export const ORDER_DETAILED_SUCCESS = 'ORDER_DETAILED_SUCCESS'
export const ORDER_DETAILED_FAIL = 'ORDER_DETAILED_FAIL'


export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_DISPLAY_REQUEST = 'ORDER_DISPLAY_REQUEST'
export const ORDER_DISPLAY_SUCCESS = 'ORDER_DISPLAY_SUCCESS'
export const ORDER_DISPLAY_FAIL = 'ORDER_DISPLAY_FAIL'
export const ORDER_DISPLAY_RESET = 'ORDER_DISPLAY_RESET'
